const express = require('express');
const { Pins, Bookings } = require('../models');
const { update } = require('../middlewares/bookings');
const { pinsController } = require('../controllers');

const router = express.Router();

router
  .route('/') 
  .get(update, pinsController.available)
  .post(pinsController.createPin)

router
  .route('/reset')
  .get(pinsController.resetBookings);

router
  .route('/book')
  .post(update,pinsController.bookSlot)

router
  .route('/set')
  .get(async (req,res) => {
    const data = [
      {
      city:"Medak",
      available:38,
      subcities:[
        {
          name:"Shivampet",
          available:11,
          fast:{
            cost:100,
            slots:[
              {
                slot:1,
                time:"9:00AM-10:00AM",
                isBooked:false,
                timeout:10,
              },
              {
                slot:2,
                time:"10:00AM-11:00AM",
                isBooked:true,
                timeout:11,
              },
              {
                slot:3,
                time:"12:00PM-1:00PM",
                isBooked:false,
                timeout:13,
              },
              {
                slot:4,
                time:"8:00PM-9:00PM",
                isBooked:false,
                timeout:21,
              },
              {
                slot:5,
                time:"9:00PM-10:00PM",
                isBooked:false,
                timeout:22,
              }
    
            ]
          },
          normal:{
            cost:75,
            slots:[
              {
                slot:1,
                time:"9:00AM-10:00AM",
                isBooked:true,
                timeout:10,
              },
              {
                slot:2,
                time:"10:00AM-11:00AM",
                isBooked:false,
                timeout:11,
              },
              {
                slot:3,
                time:"11:00AM-12:00PM",
                isBooked:false,
                timeout:12,
              },
              {
                slot:4,
                time:"1:00PM-2:00PM",
                isBooked:false,
                timeout:14,
              },
              {
                slot:5,
                time:"2:00PM-3:00PM",
                isBooked:false,
                timeout:15,
              },
              {
                slot:6,
                time:"8:00PM-9:00PM",
                isBooked:false,
                timeout:21,
              }
    
            ]
          }
        },
        {
          name:"Rathnapur",
          available:8,
          fast:{
            cost:100,
            slots:[
              {
                slot:1,
                time:"9:00AM-10:00AM",
                isBooked:false,
                timeout:10,
              },
              {
                slot:2,
                time:"10:00AM-11:00AM",
                isBooked:true,
                timeout:11,
              },
              {
                slot:3,
                time:"12:00PM-1:00PM",
                isBooked:false,
                timeout:13,
              },
              {
                slot:4,
                time:"3:00PM-4:00PM",
                isBooked:false,
                timeout:16,
              }
    
            ]
          },
          normal:{
            cost:75,
            slots:[
              {
                slot:1,
                time:"9:00AM-10:00AM",
                isBooked:true,
                timeout:10,
              },
              {
                slot:2,
                time:"10:00AM-11:00AM",
                isBooked:false,
                timeout:11,
              },
              {
                slot:3,
                time:"11:00AM-12:00PM",
                isBooked:false,
                timeout:12,
              },
              {
                slot:1,
                time:"1:00PM-2:00PM",
                isBooked:false,
                timeout:14,
              },
              {
                slot:3,
                time:"2:00PM-3:00PM",
                isBooked:false,
                timeout:15,
              },
              {
                slot:4,
                time:"3:00PM-4:00PM",
                isBooked:false,
                timeout:16,
              }
    
            ]
          }
        },
        {
          name:"Toopran",
          available:10,
          fast:{
            cost:100,
            slots:[
              {
                slot:1,
                time:"9:00AM-10:00AM",
                isBooked:false,
                timeout:10,
              },
              {
                slot:2,
                time:"10:00AM-11:00AM",
                isBooked:true,
                timeout:11,
              },
              {
                slot:3,
                time:"12:00PM-1:00PM",
                isBooked:false,
                timeout:13,
              },
              {
                slot:4,
                time:"3:00PM-4:00PM",
                isBooked:false,
                timeout:16,
              }
    
            ]
          },
          normal:{
            cost:75,
            slots:[
              {
                slot:1,
                time:"9:00AM-10:00AM",
                isBooked:true,
                timeout:10,
              },
              {
                slot:2,
                time:"10:00AM-11:00AM",
                isBooked:false,
                timeout:11,
              },
              {
                slot:3,
                time:"11:00AM-12:00PM",
                isBooked:false,
                timeout:12,
              },
              {
                slot:4,
                time:"1:00PM-2:00PM",
                isBooked:false,
                timeout:14,
              },
              {
                slot:5,
                time:"2:00PM-3:00PM",
                isBooked:false,
                timeout:15,
              },
              {
                slot:6,
                time:"3:00PM-4:00PM",
                isBooked:false,
                timeout:16,
              }
    
            ]
          }
        },
        {
          name:"BVRIT",
          available:9,
          fast:{
            cost:100,
            slots:[
              {
                slot:1,
                time:"9:00AM-10:00AM",
                isBooked:false,
                timeout:10,
              },
              {
                slot:2,
                time:"10:00AM-11:00AM",
                isBooked:true,
                timeout:11,
              },
              {
                slot:3,
                time:"12:00PM-1:00PM",
                isBooked:false,
                timeout:13,
              },
              {
                slot:4,
                time:"3:00PM-4:00PM",
                isBooked:false,
                timeout:16,
              }
    
            ]
          },
          normal:{
            cost:75,
            slots:[
              {
                slot:1,
                time:"9:00AM-10:00AM",
                isBooked:true,
                timeout:10,
              },
              {
                slot:2,
                time:"10:00AM-11:00AM",
                isBooked:false,
                timeout:11,
              },
              {
                slot:3,
                time:"11:00AM-12:00PM",
                isBooked:false,
                timeout:12,
              },
              {
                slot:4,
                time:"1:00PM-2:00PM",
                isBooked:false,
                timeout:14,
              },
              {
                slot:5,
                time:"2:00PM-3:00PM",
                isBooked:false,
                timeout:15,
              },
    
            ]
          }
        }
      ]
    },{
      city:"Sangareddy",
      available:53,
      subcities:[
        {
          name:"Hathnoor",
          available:15,
          fast:{
            cost:100,
            slots:[
              {
                slot:1,
                time:"9:00AM-10:00AM",
                isBooked:false,
                timeout:10,
              },
              {
                slot:2,
                time:"10:00AM-11:00AM",
                isBooked:true,
                timeout:11,
              },
              {
                slot:3,
                time:"12:00PM-1:00PM",
                isBooked:false,
                timeout:13,
              },
              {
                slot:4,
                time:"4:00PM-5:00PM",
                isBooked:false,
                timeout:17,
              },
              {
                slot:5,
                time:"5:00PM-6:00PM",
                isBooked:false,
                timeout:18,
              },
              {
                slot:6,
                time:"6:00PM-7:00PM",
                isBooked:false,
                timeout:19,
              },
              {
                slot:7,
                time:"7:00PM-8:00PM",
                isBooked:false,
                timeout:20,
              }
    
            ]
          },
          normal:{
            cost:75,
            slots:[
              {
                slot:1,
                time:"9:00AM-10:00AM",
                isBooked:true,
                timeout:10,
              },
              {
                slot:2,
                time:"10:00AM-11:00AM",
                isBooked:false,
                timeout:11,
              },
              {
                slot:3,
                time:"11:00AM-12:00PM",
                isBooked:false,
                timeout:12,
              },
              {
                slot:4,
                time:"1:00PM-2:00PM",
                isBooked:false,
                timeout:14,
              },
              {
                slot:5,
                time:"4:00PM-5:00PM",
                isBooked:false,
                timeout:17,
              },
              {
                slot:6,
                time:"5:00PM-6:00PM",
                isBooked:false,
                timeout:18,
              },
              {
                slot:7,
                time:"6:00PM-7:00PM",
                isBooked:false,
                timeout:19,
              },
              {
                slot:8,
                time:"7:00PM-8:00PM",
                isBooked:false,
                timeout:20,
              }
    
            ]
          }
        },
        {
          name:"Patancheru",
          available:18,
          fast:{
            cost:100,
            slots:[
              {
                slot:1,
                time:"9:00AM-10:00AM",
                isBooked:false,
                timeout:10,
              },
              {
                slot:2,
                time:"10:00AM-11:00AM",
                isBooked:true,
                timeout:11,
              },
              {
                slot:3,
                time:"12:00PM-1:00PM",
                isBooked:false,
                timeout:13,
              },
              {
                slot:4,
                time:"3:00PM-4:00PM",
                isBooked:false,
                timeout:16,
              },
              {
                slot:5,
                time:"4:00PM-5:00PM",
                isBooked:false,
                timeout:17,
              },
              {
                slot:6,
                time:"5:00PM-6:00PM",
                isBooked:false,
                timeout:18,
              },
              {
                slot:7,
                time:"6:00PM-7:00PM",
                isBooked:false,
                timeout:19,
              },
              {
                slot:8,
                time:"7:00PM-8:00PM",
                isBooked:false,
                timeout:20,
              }
    
            ]
          },
          normal:{
            cost:75,
            slots:[
              {
                slot:1,
                time:"9:00AM-10:00AM",
                isBooked:true,
                timeout:10,
              },
              {
                slot:2,
                time:"10:00AM-11:00AM",
                isBooked:false,
                timeout:11,
              },
              {
                slot:3,
                time:"11:00AM-12:00PM",
                isBooked:false,
                timeout:12,
              },
              {
                slot:4,
                time:"1:00PM-2:00PM",
                isBooked:false,
                timeout:14,
              },
              {
                slot:5,
                time:"2:00PM-3:00PM",
                isBooked:false,
                timeout:15,
              },
              {
                slot:6,
                time:"3:00PM-4:00PM",
                isBooked:false,
                timeout:16,
              },
              {
                slot:7,
                time:"4:00PM-5:00PM",
                isBooked:false,
                timeout:17,
              },
              {
                slot:8,
                time:"5:00PM-6:00PM",
                isBooked:false,
                timeout:18,
              },
              {
                slot:9,
                time:"6:00PM-7:00PM",
                isBooked:false,
                timeout:19,
              },
              {
                slot:10,
                time:"7:00PM-8:00PM",
                isBooked:false,
                timeout:20,
              }
    
            ]
          }
        },
        {
          name:"Jogipet",
          available:10,
          fast:{
            cost:100,
            slots:[
              {
                slot:1,
                time:"9:00AM-10:00AM",
                isBooked:false,
                timeout:10,
              },
              {
                slot:2,
                time:"10:00AM-11:00AM",
                isBooked:true,
                timeout:11,
              },
              {
                slot:3,
                time:"12:00PM-1:00PM",
                isBooked:false,
                timeout:13,
              },
              {
                slot:4,
                time:"5:00PM-6:00PM",
                isBooked:false,
                timeout:18,
              }
    
            ]
          },
          normal:{
            cost:75,
            slots:[
              {
                slot:1,
                time:"9:00AM-10:00AM",
                isBooked:true,
                timeout:10,
              },
              {
                slot:2,
                time:"10:00AM-11:00AM",
                isBooked:false,
                timeout:11,
              },
              {
                slot:3,
                time:"11:00AM-12:00PM",
                isBooked:false,
                timeout:12,
              },
              {
                slot:4,
                time:"1:00PM-2:00PM",
                isBooked:false,
                timeout:14,
              },
              {
                slot:5,
                time:"2:00PM-3:00PM",
                isBooked:false,
                timeout:15,
              },
              {
                slot:6,
                time:"6:00PM-7:00PM",
                isBooked:false,
                timeout:19,
              }
    
            ]
          }
        },
        {
          name:"Koudipally",
          available:10,
          fast:{
            cost:100,
            slots:[
              {
                slot:1,
                time:"9:00AM-10:00AM",
                isBooked:false,
                timeout:10,
              },
              {
                slot:2,
                time:"10:00AM-11:00AM",
                isBooked:true,
                timeout:11,
              },
              {
                slot:3,
                time:"12:00PM-1:00PM",
                isBooked:false,
                timeout:13,
              },
              {
                slot:4,
                time:"3:00PM-4:00PM",
                isBooked:false,
                timeout:16,
              }
    
            ]
          },
          normal:{
            cost:75,
            slots:[
              {
                slot:1,
                time:"9:00AM-10:00AM",
                isBooked:true,
                timeout:10,
              },
              {
                slot:2,
                time:"10:00AM-11:00AM",
                isBooked:false,
                timeout:11,
              },
              {
                slot:3,
                time:"11:00AM-12:00PM",
                isBooked:false,
                timeout:12,
              },
              {
                slot:4,
                time:"1:00PM-2:00PM",
                isBooked:false,
                timeout:14,
              },
              {
                slot:5,
                time:"2:00PM-3:00PM",
                isBooked:false,
                timeout:15,
              },
              {
                slot:6,
                time:"3:00PM-4:00PM",
                isBooked:false,
                timeout:16,
              }
    
            ]
          }
        }
      ]
    },{
      city:"Narsapur",
      available:10,
      subcities:[
        {
          name:"Location1",
          available:9,
          fast:{
            cost:100,
            slots:[
              {
                slot:1,
                time:"9:00AM-10:00AM",
                isBooked:false,
                timeout:10,
              },
              {
                slot:2,
                time:"10:00AM-11:00AM",
                isBooked:true,
                timeout:11,
              },
              {
                slot:3,
                time:"12:00PM-1:00PM",
                isBooked:false,
                timeout:13,
              },
              {
                slot:1,
                time:"3:00PM-4:00PM",
                isBooked:false,
                timeout:16,
              }
    
            ]
          },
          normal:{
            cost:75,
            slots:[
              {
                slot:1,
                time:"9:00AM-10:00AM",
                isBooked:true,
                timeout:10,
              },
              {
                slot:2,
                time:"10:00AM-11:00AM",
                isBooked:false,
                timeout:11,
              },
              {
                slot:3,
                time:"11:00AM-12:00PM",
                isBooked:false,
                timeout:13,
              },
              {
                slot:1,
                time:"1:00PM-2:00PM",
                isBooked:false,
                timeout:16,
              },
              {
                slot:3,
                time:"2:00PM-3:00PM",
                isBooked:false,
                timeout:13,
              },
              {
                slot:1,
                time:"3:00PM-4:00PM",
                isBooked:false,
                timeout:16,
              }
    
            ]
          }
        },
        {
          name:"Location1",
          available:9,
          fast:{
            cost:100,
            slots:[
              {
                slot:1,
                time:"9:00AM-10:00AM",
                isBooked:false,
                timeout:10,
              },
              {
                slot:2,
                time:"10:00AM-11:00AM",
                isBooked:true,
                timeout:11,
              },
              {
                slot:3,
                time:"12:00PM-1:00PM",
                isBooked:false,
                timeout:13,
              },
              {
                slot:1,
                time:"3:00PM-4:00PM",
                isBooked:false,
                timeout:16,
              }
    
            ]
          },
          normal:{
            cost:75,
            slots:[
              {
                slot:1,
                time:"9:00AM-10:00AM",
                isBooked:true,
                timeout:10,
              },
              {
                slot:2,
                time:"10:00AM-11:00AM",
                isBooked:false,
                timeout:11,
              },
              {
                slot:3,
                time:"11:00AM-12:00PM",
                isBooked:false,
                timeout:13,
              },
              {
                slot:1,
                time:"1:00PM-2:00PM",
                isBooked:false,
                timeout:16,
              },
              {
                slot:3,
                time:"2:00PM-3:00PM",
                isBooked:false,
                timeout:13,
              },
              {
                slot:1,
                time:"3:00PM-4:00PM",
                isBooked:false,
                timeout:16,
              }
    
            ]
          }
        },
        {
          name:"Location1",
          available:9,
          fast:{
            cost:100,
            slots:[
              {
                slot:1,
                time:"9:00AM-10:00AM",
                isBooked:false,
                timeout:10,
              },
              {
                slot:2,
                time:"10:00AM-11:00AM",
                isBooked:true,
                timeout:11,
              },
              {
                slot:3,
                time:"12:00PM-1:00PM",
                isBooked:false,
                timeout:13,
              },
              {
                slot:1,
                time:"3:00PM-4:00PM",
                isBooked:false,
                timeout:16,
              }
    
            ]
          },
          normal:{
            cost:75,
            slots:[
              {
                slot:1,
                time:"9:00AM-10:00AM",
                isBooked:true,
                timeout:10,
              },
              {
                slot:2,
                time:"10:00AM-11:00AM",
                isBooked:false,
                timeout:11,
              },
              {
                slot:3,
                time:"11:00AM-12:00PM",
                isBooked:false,
                timeout:13,
              },
              {
                slot:1,
                time:"1:00PM-2:00PM",
                isBooked:false,
                timeout:16,
              },
              {
                slot:3,
                time:"2:00PM-3:00PM",
                isBooked:false,
                timeout:13,
              },
              {
                slot:1,
                time:"3:00PM-4:00PM",
                isBooked:false,
                timeout:16,
              }
    
            ]
          }
        },
        {
          name:"Location1",
          available:9,
          fast:{
            cost:100,
            slots:[
              {
                slot:1,
                time:"9:00AM-10:00AM",
                isBooked:false,
                timeout:10,
              },
              {
                slot:2,
                time:"10:00AM-11:00AM",
                isBooked:true,
                timeout:11,
              },
              {
                slot:3,
                time:"12:00PM-1:00PM",
                isBooked:false,
                timeout:13,
              },
              {
                slot:1,
                time:"3:00PM-4:00PM",
                isBooked:false,
                timeout:16,
              }
    
            ]
          },
          normal:{
            cost:75,
            slots:[
              {
                slot:1,
                time:"9:00AM-10:00AM",
                isBooked:true,
                timeout:10,
              },
              {
                slot:2,
                time:"10:00AM-11:00AM",
                isBooked:false,
                timeout:11,
              },
              {
                slot:3,
                time:"11:00AM-12:00PM",
                isBooked:false,
                timeout:13,
              },
              {
                slot:1,
                time:"1:00PM-2:00PM",
                isBooked:false,
                timeout:16,
              },
              {
                slot:3,
                time:"2:00PM-3:00PM",
                isBooked:false,
                timeout:13,
              },
              {
                slot:1,
                time:"3:00PM-4:00PM",
                isBooked:false,
                timeout:16,
              }
    
            ]
          }
        }
      ]
    },{
      city:"Jogipet",
      available:10,
      subcities:[
        {
          name:"Location1",
          available:9,
          fast:{
            cost:100,
            slots:[
              {
                slot:1,
                time:"9:00AM-10:00AM",
                isBooked:false,
                timeout:10,
              },
              {
                slot:2,
                time:"10:00AM-11:00AM",
                isBooked:true,
                timeout:11,
              },
              {
                slot:3,
                time:"12:00PM-1:00PM",
                isBooked:false,
                timeout:13,
              },
              {
                slot:1,
                time:"3:00PM-4:00PM",
                isBooked:false,
                timeout:16,
              }
    
            ]
          },
          normal:{
            cost:75,
            slots:[
              {
                slot:1,
                time:"9:00AM-10:00AM",
                isBooked:true,
                timeout:10,
              },
              {
                slot:2,
                time:"10:00AM-11:00AM",
                isBooked:false,
                timeout:11,
              },
              {
                slot:3,
                time:"11:00AM-12:00PM",
                isBooked:false,
                timeout:13,
              },
              {
                slot:1,
                time:"1:00PM-2:00PM",
                isBooked:false,
                timeout:16,
              },
              {
                slot:3,
                time:"2:00PM-3:00PM",
                isBooked:false,
                timeout:13,
              },
              {
                slot:1,
                time:"3:00PM-4:00PM",
                isBooked:false,
                timeout:16,
              }
    
            ]
          }
        },
        {
          name:"Location1",
          available:9,
          fast:{
            cost:100,
            slots:[
              {
                slot:1,
                time:"9:00AM-10:00AM",
                isBooked:false,
                timeout:10,
              },
              {
                slot:2,
                time:"10:00AM-11:00AM",
                isBooked:true,
                timeout:11,
              },
              {
                slot:3,
                time:"12:00PM-1:00PM",
                isBooked:false,
                timeout:13,
              },
              {
                slot:1,
                time:"3:00PM-4:00PM",
                isBooked:false,
                timeout:16,
              }
    
            ]
          },
          normal:{
            cost:75,
            slots:[
              {
                slot:1,
                time:"9:00AM-10:00AM",
                isBooked:true,
                timeout:10,
              },
              {
                slot:2,
                time:"10:00AM-11:00AM",
                isBooked:false,
                timeout:11,
              },
              {
                slot:3,
                time:"11:00AM-12:00PM",
                isBooked:false,
                timeout:13,
              },
              {
                slot:1,
                time:"1:00PM-2:00PM",
                isBooked:false,
                timeout:16,
              },
              {
                slot:3,
                time:"2:00PM-3:00PM",
                isBooked:false,
                timeout:13,
              },
              {
                slot:1,
                time:"3:00PM-4:00PM",
                isBooked:false,
                timeout:16,
              }
    
            ]
          }
        },
        {
          name:"Location1",
          available:9,
          fast:{
            cost:100,
            slots:[
              {
                slot:1,
                time:"9:00AM-10:00AM",
                isBooked:false,
                timeout:10,
              },
              {
                slot:2,
                time:"10:00AM-11:00AM",
                isBooked:true,
                timeout:11,
              },
              {
                slot:3,
                time:"12:00PM-1:00PM",
                isBooked:false,
                timeout:13,
              },
              {
                slot:1,
                time:"3:00PM-4:00PM",
                isBooked:false,
                timeout:16,
              }
    
            ]
          },
          normal:{
            cost:75,
            slots:[
              {
                slot:1,
                time:"9:00AM-10:00AM",
                isBooked:true,
                timeout:10,
              },
              {
                slot:2,
                time:"10:00AM-11:00AM",
                isBooked:false,
                timeout:11,
              },
              {
                slot:3,
                time:"11:00AM-12:00PM",
                isBooked:false,
                timeout:13,
              },
              {
                slot:1,
                time:"1:00PM-2:00PM",
                isBooked:false,
                timeout:16,
              },
              {
                slot:3,
                time:"2:00PM-3:00PM",
                isBooked:false,
                timeout:13,
              },
              {
                slot:1,
                time:"3:00PM-4:00PM",
                isBooked:false,
                timeout:16,
              }
    
            ]
          }
        },
        {
          name:"Location1",
          available:9,
          fast:{
            cost:100,
            slots:[
              {
                slot:1,
                time:"9:00AM-10:00AM",
                isBooked:false,
                timeout:10,
              },
              {
                slot:2,
                time:"10:00AM-11:00AM",
                isBooked:true,
                timeout:11,
              },
              {
                slot:3,
                time:"12:00PM-1:00PM",
                isBooked:false,
                timeout:13,
              },
              {
                slot:1,
                time:"3:00PM-4:00PM",
                isBooked:false,
                timeout:16,
              }
    
            ]
          },
          normal:{
            cost:75,
            slots:[
              {
                slot:1,
                time:"9:00AM-10:00AM",
                isBooked:true,
                timeout:10,
              },
              {
                slot:2,
                time:"10:00AM-11:00AM",
                isBooked:false,
                timeout:11,
              },
              {
                slot:3,
                time:"11:00AM-12:00PM",
                isBooked:false,
                timeout:13,
              },
              {
                slot:1,
                time:"1:00PM-2:00PM",
                isBooked:false,
                timeout:16,
              },
              {
                slot:3,
                time:"2:00PM-3:00PM",
                isBooked:false,
                timeout:13,
              },
              {
                slot:1,
                time:"3:00PM-4:00PM",
                isBooked:false,
                timeout:16,
              }
    
            ]
          }
        }
      ]
    },{
      city:"Hyderabad",
      available:10,
      subcities:[
        {
          name:"Location1",
          available:9,
          fast:{
            cost:100,
            slots:[
              {
                slot:1,
                time:"9:00AM-10:00AM",
                isBooked:false,
                timeout:10,
              },
              {
                slot:2,
                time:"10:00AM-11:00AM",
                isBooked:true,
                timeout:11,
              },
              {
                slot:3,
                time:"12:00PM-1:00PM",
                isBooked:false,
                timeout:13,
              },
              {
                slot:1,
                time:"3:00PM-4:00PM",
                isBooked:false,
                timeout:16,
              }
    
            ]
          },
          normal:{
            cost:75,
            slots:[
              {
                slot:1,
                time:"9:00AM-10:00AM",
                isBooked:true,
                timeout:10,
              },
              {
                slot:2,
                time:"10:00AM-11:00AM",
                isBooked:false,
                timeout:11,
              },
              {
                slot:3,
                time:"11:00AM-12:00PM",
                isBooked:false,
                timeout:13,
              },
              {
                slot:1,
                time:"1:00PM-2:00PM",
                isBooked:false,
                timeout:16,
              },
              {
                slot:3,
                time:"2:00PM-3:00PM",
                isBooked:false,
                timeout:13,
              },
              {
                slot:1,
                time:"3:00PM-4:00PM",
                isBooked:false,
                timeout:16,
              }
    
            ]
          }
        },
        {
          name:"Location1",
          available:9,
          fast:{
            cost:100,
            slots:[
              {
                slot:1,
                time:"9:00AM-10:00AM",
                isBooked:false,
                timeout:10,
              },
              {
                slot:2,
                time:"10:00AM-11:00AM",
                isBooked:true,
                timeout:11,
              },
              {
                slot:3,
                time:"12:00PM-1:00PM",
                isBooked:false,
                timeout:13,
              },
              {
                slot:1,
                time:"3:00PM-4:00PM",
                isBooked:false,
                timeout:16,
              }
    
            ]
          },
          normal:{
            cost:75,
            slots:[
              {
                slot:1,
                time:"9:00AM-10:00AM",
                isBooked:true,
                timeout:10,
              },
              {
                slot:2,
                time:"10:00AM-11:00AM",
                isBooked:false,
                timeout:11,
              },
              {
                slot:3,
                time:"11:00AM-12:00PM",
                isBooked:false,
                timeout:13,
              },
              {
                slot:1,
                time:"1:00PM-2:00PM",
                isBooked:false,
                timeout:16,
              },
              {
                slot:3,
                time:"2:00PM-3:00PM",
                isBooked:false,
                timeout:13,
              },
              {
                slot:1,
                time:"3:00PM-4:00PM",
                isBooked:false,
                timeout:16,
              }
    
            ]
          }
        },
        {
          name:"Location1",
          available:9,
          fast:{
            cost:100,
            slots:[
              {
                slot:1,
                time:"9:00AM-10:00AM",
                isBooked:false,
                timeout:10,
              },
              {
                slot:2,
                time:"10:00AM-11:00AM",
                isBooked:true,
                timeout:11,
              },
              {
                slot:3,
                time:"12:00PM-1:00PM",
                isBooked:false,
                timeout:13,
              },
              {
                slot:1,
                time:"3:00PM-4:00PM",
                isBooked:false,
                timeout:16,
              }
    
            ]
          },
          normal:{
            cost:75,
            slots:[
              {
                slot:1,
                time:"9:00AM-10:00AM",
                isBooked:true,
                timeout:10,
              },
              {
                slot:2,
                time:"10:00AM-11:00AM",
                isBooked:false,
                timeout:11,
              },
              {
                slot:3,
                time:"11:00AM-12:00PM",
                isBooked:false,
                timeout:13,
              },
              {
                slot:1,
                time:"1:00PM-2:00PM",
                isBooked:false,
                timeout:16,
              },
              {
                slot:3,
                time:"2:00PM-3:00PM",
                isBooked:false,
                timeout:13,
              },
              {
                slot:1,
                time:"3:00PM-4:00PM",
                isBooked:false,
                timeout:16,
              }
    
            ]
          }
        },
        {
          name:"Location1",
          available:9,
          fast:{
            cost:100,
            slots:[
              {
                slot:1,
                time:"9:00AM-10:00AM",
                isBooked:false,
                timeout:10,
              },
              {
                slot:2,
                time:"10:00AM-11:00AM",
                isBooked:true,
                timeout:11,
              },
              {
                slot:3,
                time:"12:00PM-1:00PM",
                isBooked:false,
                timeout:13,
              },
              {
                slot:1,
                time:"3:00PM-4:00PM",
                isBooked:false,
                timeout:16,
              }
    
            ]
          },
          normal:{
            cost:75,
            slots:[
              {
                slot:1,
                time:"9:00AM-10:00AM",
                isBooked:true,
                timeout:10,
              },
              {
                slot:2,
                time:"10:00AM-11:00AM",
                isBooked:false,
                timeout:11,
              },
              {
                slot:3,
                time:"11:00AM-12:00PM",
                isBooked:false,
                timeout:13,
              },
              {
                slot:1,
                time:"1:00PM-2:00PM",
                isBooked:false,
                timeout:16,
              },
              {
                slot:3,
                time:"2:00PM-3:00PM",
                isBooked:false,
                timeout:13,
              },
              {
                slot:1,
                time:"3:00PM-4:00PM",
                isBooked:false,
                timeout:16,
              }
    
            ]
          }
        }
      ]
    }
    ]

    const re = []
    for( const each of data) {
      const v = await Pins.create(each);
      re.push(v);
    }
    return res.json({status: true, data: re})
  })

module.exports = router ;